Parameters:
  EC2InstanceId:
    Type: String
    Description: ID of the EC2 instance to attach the profile to (e.g., i-0000d8667e6fa999999)
    AllowedPattern: ^i-[a-zA-Z0-9]+$
    ConstraintDescription: Must be a valid EC2 instance ID starting with 'i-'

Resources:
  RDSPSQLPatchPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - rds:DescribeDBInstances
              - rds:ModifyDBInstance
              - rds:RebootDBInstance
              - rds:CreateDBSnapshot
              - rds:DescribeDBSnapshots
              - rds:DescribeDBEngineVersions
              - rds:DescribeOrderableDBInstanceOptions
              - rds:DescribeDBParameterGroups
              - rds:CreateDBParameterGroup
              - rds:ModifyDBParameterGroup
              - rds:DescribeDBParameters
              - rds:DescribePendingMaintenanceActions
              - rds:ApplyPendingMaintenanceAction
              - rds:AddTagsToResource
              - rds:ListTagsForResource
            Resource: 
              - arn:aws:rds:*:*:db:*
              - arn:aws:rds:*:*:pg:*
              - arn:aws:rds:*:*:snapshot:*
          - Effect: Allow
            Action:
              - iam:GetRole
              - iam:ListRoles
            Resource: arn:aws:iam::*:role/rds-psql-patch-*
          - Effect: Allow
            Action:
              - cloudwatch:PutMetricData
              - cloudwatch:GetMetricStatistics
              - cloudwatch:ListMetrics
            Resource: arn:aws:cloudwatch:*:*:metric-stream/rds-psql-patch-*
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
              - logs:GetLogEvents
            Resource:
              - arn:aws:logs:*:*:log-group:rds-psql-patch-*
              - arn:aws:logs:*:*:log-group:rds-psql-patch-*:log-stream:*
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::rds-psql-patch-*
              - arn:aws:s3:::rds-psql-patch-*/*
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:*:*:secret:rds*
          - Effect: Allow
            Action:
              - sns:Publish
            Resource: "arn:aws:sns:*:*:rds-psql-patch-*"
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
              - kms:CreateGrant
              - kms:ReEncrypt*
              - kms:DescribeKey
            Resource:
              - arn:aws:kms:*:*:key/rds-psql-patch-*
          - Effect: Allow
            Action:
              - ec2:DescribeInstances
              - ec2:DescribeTags
            Resource: 
              - !Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/${EC2InstanceId}'

  RDSPSQLPatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref RDSPSQLPatchPolicy
      Path: /
      Tags:
        - Key: Purpose
          Value: RDSPostgreSQLPatching

  RDSPSQLPatchInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: RDSPSQLPatchProfile
      Path: /
      Roles:
        - !Ref RDSPSQLPatchRole

Outputs:
  RoleArn:
    Description: ARN of the created IAM Role
    Value: !GetAtt RDSPSQLPatchRole.Arn
  PolicyArn:
    Description: ARN of the created IAM Policy
    Value: !Ref RDSPSQLPatchPolicy
  InstanceProfileArn:
    Description: ARN of the created Instance Profile
    Value: !GetAtt RDSPSQLPatchInstanceProfile.Arn
