AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RDSMasterUsername:
    Type: String
    Description: RDS Master Username
  RDSSecurityGroups:
    Type: List<String>
    Description: Security groups to use
Resources:
  RDSParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      DBParameterGroupName: rds-psql-patch-instance-v14-param-group-1
      Family: postgres14
      Description: "rds postgresql instance v14 parameter group 1"
      Parameters:
        rds.force_ssl: 1  # Forces SSL connections
        rds.logical_replication: 1  # Enables logical replication
      Tags:
        - Key: Name
          Value: rds-psql-patch-instance-v14-param-group-1
        - Key: StackName
          Value: !Ref 'AWS::StackName'

  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    DependsOn: RDSParameterGroup
    Properties:
      DeletionProtection: true
      PubliclyAccessible: false
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: '14.9'
      MasterUsername:
        - !Ref RDSMasterUsername
        - NoEcho: true
      ManageMasterUserPassword: true
      DBParameterGroupName: !Ref RDSParameterGroup
      AllocatedStorage: 200
      BackupRetentionPeriod: 7
      MultiAZ: true
      VPCSecurityGroups: !Ref RDSSecurityGroups
      DBSubnetGroupName: rds-psql-patch-test-db-subnet-group
      DBName: rdspatch
      StorageEncrypted: true
      Tags:
        - Key: Name
          Value: rds-psql-patch-instance-1
        - Key: StackName
          Value: !Ref 'AWS::StackName'
